# Generated by Django 2.0 on 2019-05-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('cook_id', models.AutoField(primary_key=True, serialize=False)),
                ('cook_image', models.ImageField(upload_to='')),
                ('cook_brief_content', models.TextField()),
                ('cook_praise', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('diet_id', models.AutoField(primary_key=True, serialize=False)),
                ('diet_name', models.TextField()),
                ('diet_image', models.ImageField(upload_to='')),
                ('diet_brief_content', models.TextField()),
                ('diet_material', models.TextField()),
                ('diet_nutrient', models.TextField()),
                ('diet_location', models.TextField()),
                ('diet_praise', models.IntegerField()),
                ('diet_cook_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('uesr_image', models.ImageField(upload_to='')),
                ('user_manager', models.BooleanField()),
            ],
        ),
    ]
