# Generated by Django 2.2.1 on 2019-09-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('cook_id', models.AutoField(primary_key=True, serialize=False)),
                ('cook_name', models.TextField(default=' ')),
                ('cook_image', models.TextField()),
                ('cook_brief_content', models.TextField()),
                ('cook_praise', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('diet_id', models.AutoField(primary_key=True, serialize=False)),
                ('diet_name', models.TextField()),
                ('diet_image', models.TextField()),
                ('diet_material', models.TextField()),
                ('diet_nutrient', models.TextField()),
                ('diet_location', models.TextField()),
                ('diet_price', models.IntegerField()),
                ('diet_praise', models.IntegerField()),
                ('diet_cook_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_class', models.TextField()),
                ('que_time', models.TextField()),
                ('que_text', models.TextField()),
                ('que_image', models.ImageField(upload_to='')),
                ('que_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_user_id', models.TextField()),
                ('log_diet_id', models.IntegerField()),
                ('log_diet_praise', models.BooleanField()),
                ('log_diet_evaluation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('user_image', models.TextField()),
                ('user_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution1', models.IntegerField()),
                ('attribution2', models.IntegerField()),
                ('attribution3', models.IntegerField()),
                ('attribution4', models.IntegerField()),
                ('attribution5', models.IntegerField()),
                ('attribution6', models.IntegerField()),
                ('attribution7', models.IntegerField()),
                ('attribution8', models.IntegerField()),
                ('attribution9', models.IntegerField()),
                ('diet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxshahe.Diet')),
            ],
        ),
    ]
