# Generated by Django 2.0 on 2019-05-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxshahe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='cook_name',
            field=models.TextField(default=' '),
        ),
    ]
