# Generated by Django 2.0 on 2019-05-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxshahe', '0002_cook_cook_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='diet_cook_id',
            field=models.IntegerField(),
        ),
    ]
