# Generated by Django 2.0 on 2019-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxshahe', '0004_remove_diet_diet_brief_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_user_id', models.IntegerField()),
                ('log_diet_id', models.IntegerField()),
                ('log_diet_praise', models.BooleanField()),
                ('log_diet_evaluation', models.TextField(default=None)),
            ],
        ),
    ]
