# Generated by Django 2.0 on 2019-05-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxshahe', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='cook_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diet',
            name='diet_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='uesr_image',
            field=models.TextField(),
        ),
    ]
