# Generated by Django 2.0 on 2019-05-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxshahe', '0006_auto_20190530_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uesr_image',
            new_name='user_image',
        ),
    ]
