# Generated by Django 2.0 on 2019-05-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxshahe', '0009_auto_20190530_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='diet_name',
        ),
    ]
