# Generated by Django 2.0 on 2019-05-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxshahe', '0010_remove_attribution_diet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_manager',
            field=models.BooleanField(default=False),
        ),
    ]
