# Generated by Django 2.0 on 2019-05-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxshahe', '0012_auto_20190530_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_user_id',
            field=models.TextField(),
        ),
    ]
