# Generated by Django 2.0 on 2019-05-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxshahe', '0013_auto_20190530_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_diet_evaluation',
            field=models.TextField(),
        ),
    ]
