# Generated by Django 2.0 on 2019-05-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxshahe', '0014_auto_20190530_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster1', models.FloatField(max_length=13)),
                ('cluster2', models.FloatField(max_length=13)),
                ('cluster3', models.FloatField(max_length=13)),
                ('cluster4', models.FloatField(max_length=13)),
                ('cluster5', models.FloatField(max_length=13)),
                ('cluster6', models.FloatField(max_length=13)),
                ('cluster7', models.FloatField(max_length=13)),
                ('cluster8', models.FloatField(max_length=13)),
                ('cluster9', models.FloatField(max_length=13)),
            ],
        ),
    ]
